Update to create 1.8 binaries but still default to 11 runtime

diff --git a/pkg/etc/init.d/wavefront-proxy b/pkg/etc/init.d/wavefront-proxy
--- a/pkg/etc/init.d/wavefront-proxy
+++ b/pkg/etc/init.d/wavefront-proxy
@@ -35,7 +35,7 @@ user="wavefront"
 wavefront_dir="/opt/wavefront"
 proxy_dir=${PROXY_DIR:-$wavefront_dir/wavefront-proxy}
 config_dir=${CONFIG_DIR:-/etc/wavefront/wavefront-proxy}
-proxy_jre_dir="$proxy_dir/proxy-jre-11"
+proxy_jre_dir="$proxy_dir/proxy-jre"
 export JAVA_HOME=${PROXY_JAVA_HOME:-$proxy_jre_dir}
 conf_file=$CONF_FILE
 if [[ -z $conf_file ]]; then
@@ -85,6 +85,11 @@ if [[ -r $proxy_launch_conf ]]; then
 	fi
 fi
 
+# Workaround for environments with locked-down internet access where approved traffic goes through HTTP proxy.
+# If JRE cannot be found in $proxy_jre_dir (most likely because its download failed during installation), and
+# $PROXY_JAVA_HOME pointing to a user-defined JRE is not defined either, we'll try to read HTTP proxy settings
+# from wavefront.conf, if any, and try to download the JRE again. Ideally we should go back to bundling JRE
+# and not having to worry about accessibility of external resources.
 download_jre() {
     [[ -d $proxy_jre_dir ]] || mkdir -p $proxy_jre_dir
 
@@ -109,23 +114,20 @@ download_jre() {
     rm /tmp/jre.tar.gz || true
 }
 
-# Workaround for environments with locked-down internet access where approved traffic goes through HTTP proxy.
-# If JRE cannot be found in $proxy_jre_dir (most likely because its download failed during installation), and
-# $PROXY_JAVA_HOME pointing to a user-defined JRE is not defined either, we'll try to read HTTP proxy settings
-# from wavefront.conf, if any, and try to download the JRE again. Ideally we should go back to bundling JRE
-# and not having to worry about accessibility of external resources.
+# If $PROXY_JAVA_HOME is not defined and there is no JRE in $proxy_jre_dir, try to auto-detect
+# locally installed JDK first. We will accept 1.8, 9, 10, 11.
 if [[ -z "$PROXY_JAVA_HOME" && ! -r $proxy_jre_dir/bin/java ]]; then
     if type -p java; then
         JAVA_VERSION=$(java -version 2>&1 | head -1 | cut -d'"' -f2 | sed '/^1\./s///' | cut -d'.' -f1)
-        if [[ $JAVA_VERSION == "11" ]]; then
+        if [[ $JAVA_VERSION == "11" || $JAVA_VERSION == "10" || $JAVA_VERSION == "9" || $JAVA_VERSION == "1.8" ]]; then
             JAVA_HOME=$($(dirname $(dirname $(readlink -f $(which javac)))))
-            echo "Using Java 11 detected in $JAVA_HOME" >&2
+            echo "Using Java runtime $JAVA_VERSION detected in $JAVA_HOME" >&2
         else
-            echo "Java 11 not found - trying to download and install" >&2
+            echo "Java runtime [1.8; 12) not found - trying to download and install" >&2
             download_jre
         fi
     else
-        echo "Java 11 not found - trying to download and install" >&2
+        echo "Java runtime not found - trying to download and install" >&2
         download_jre
     fi
 fi
